### ISSUE TITLE
Avoid use of deprecated "RELEASE" metaversion

### ISSUE THREAD

**Issue by jstaffans** [boot-clj/boot-new#14]
Handy as it might be, the use of `RELEASE` metaversion has been deprecated in Maven for a [long time](http://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency). Some tools may not support it - I am using Cursive Clojure and therefore auto-generate a `project.clj` file from the `build.boot` file to make the editor aware of my dependencies, but I had to replace `[org.clojure/clojure "RELEASE"]` with `[org.clojure/clojure "1.8.0"]` to get the core namespaces picked up.

I assume this is because IntelliJ IDEA uses Maven 3, which no longer supports the `RELEASE` metaversion.

**Comment by seancorfield** [comment]
Interesting. The `"RELEASE"` and `"(0.0.0,)"` meta-versions are how Leiningen's `new` task works internally and both Boot and Leiningen support this through their use of Aether. I'll talk to @cursive-ide (Colin) and @micha about this to see what to do. Given that Boot and Leiningen _do_ support this, I'm inclined to leave it as-is -- and perhaps the process you use to generate `project.clj` for Cursive should change to accommodate this?

**Comment by cursive-ghost** [comment]
Cursive actually does use Leiningen directly under the hood, so if this works in lein it should work in Cursive too. @jstaffans if it doesn't, that might be worth a bug report in the Cursive tracker and I'll investigate it.

**Comment by jstaffans** [comment]
will do that @cursive-ide, thanks!
