### ISSUE TITLE
Getting Started example fails

### ISSUE THREAD

**Issue by mobileink** [boot-clj/boot-new#17]
$ boot -d seancorfield/boot-new new -t quex -n quex

Could not load template, failed with: Failed to collect dependencies for [#object[org.sonatype.aether.graph.Dependency 0x5c481da6 "seancorfield:boot-new:jar:RELEASE (compile)"] #object[org.sonatype.aether.graph.Dependency 0x292ac9f "seancorfield:boot-new:jar:RELEASE (compile)"] #object[org.sonatype.aether.graph.Dependency 0x6b82fc0a "seancorfield:boot-new:jar:RELEASE (compile)"] #object[org.sonatype.aether.graph.Dependency 0x64712baa "stencil:stencil:jar:0.5.0 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x41e9d96a "leiningen-core:leiningen-core:jar:2.5.3 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x5fc0dff4 "slingshot:slingshot:jar:0.10.3 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x6faf3d48 "quex:lein-template:jar:RELEASE (compile)"]]
             clojure.lang.ExceptionInfo: boot.App$Exit: 1
    data: {:file
           "/var/folders/wz/dx0cgvqx5qn802qmc3d4hcfr0000gn/T/boot.user5710570556501181879.clj",
           :line 7}
java.util.concurrent.ExecutionException: boot.App$Exit: 1
                          boot.App$Exit: 1
boot.new-helpers/resolve-remote-template  new_helpers.clj:   65
    boot.new-helpers/resolve-template/fn  new_helpers.clj:   74
       boot.new-helpers/resolve-template  new_helpers.clj:   71
                boot.new-helpers/create\*  new_helpers.clj:  105
                 boot.new-helpers/create  new_helpers.clj:  118
                                     ...
                boot.new/eval69/fn/fn/fn          new.clj:   43
                     boot.core/run-tasks         core.clj:  794
                       boot.core/boot/fn         core.clj:  804
     clojure.core/binding-conveyor-fn/fn         core.clj: 1916

$ boot -V
# http://boot-clj.com
# Sun Apr 03 09:18:51 CDT 2016

BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.5.5

 $ boot -b
(ns boot.user (:use boot.core boot.util boot.task.built-in))

(clojure.core/comment "start boot script")

(clojure.core/comment "end boot script")

(clojure.core/let [boot?**1228__auto** true](clojure.core/if-not boot?__1228__auto__ %28clojure.core/when-let [main__1229__auto__ %28clojure.core/resolve %28quote boot.user/-main%29%29] %28main__1229__auto__%29%29 %28boot.core/boot)))

**Comment by mobileink** [comment]
never mind

**Comment by seancorfield** [comment]
I assume neither quex/boot-template or quex/lein-template exist in released form?

**Comment by mobileink** [comment]
On Apr 3, 2016 4:14 PM, "Sean Corfield" notifications@github.com wrote:

> I assume neither quex/boot-template or quex/lein-template exist in
> released form?

Not even a template, just a dumb mistake.  Sorry for the noise.  And thanks
for the awesome lib.
