### ISSUE TITLE
template template

### ISSUE THREAD

**Issue by antonharald** [boot-clj/boot-new#25]
I'm having troubles using the built-in template 'template'. Check out this shell log. Am I doing this correctly?

bash-4.3$ cd ~/tmp
bash-4.3$ boot -d seancorfield/boot-new new -t template -n testt
Generating fresh 'boot new' template project.
bash-4.3$ cd testt
bash-4.3$ boot build
Warning: version conflict detected: org.clojure/clojure version changes from 1.6.0 to 1.9.0-alpha11
Warning: version conflict detected: org.clojure/clojure version changes from 1.6.0 to 1.9.0-alpha11
Writing pom.xml and pom.properties...
Writing boot-template-0.1.0-SNAPSHOT.jar...
Installing boot-template-0.1.0-SNAPSHOT.jar...
bash-4.3$ cd ..
bash-4.3$ boot -d seancorfield/boot-new new -t testt -n my

Could not load template, failed with: Failed to collect dependencies for [#object[org.sonatype.aether.graph.Dependency 0x473b87b "seancorfield:boot-new:jar:RELEASE (compile)"] #object[org.sonatype.aether.graph.Dependency 0xa023368 "seancorfield:boot-new:jar:0.4.6 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x4005a3ee "seancorfield:boot-new:jar:0.4.6 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x8ee1c05 "ancient-clj:ancient-clj:jar:0.2.1 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x11c7dd03 "samestep:boot-refresh:jar:0.1.0 (compile)"] #object[org.sonatype.aether.graph.Dependency 0xac53520 "stencil:stencil:jar:0.5.0 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x67b2ed45 "leiningen-core:leiningen-core:jar:2.5.3 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x1f44cb82 "slingshot:slingshot:jar:0.10.3 (compile)"] #object[org.sonatype.aether.graph.Dependency 0x304422ac "testt:lein-template:jar:RELEASE (compile)"]]
clojure.lang.ExceptionInfo: 1
    data: {:file "/tmp/boot.user8245379805523694012.clj", :line 23}
             boot.App$Exit: 1
boot.new-helpers/resolve-remote-template/invokeStatic  new_helpers.clj:   65
             boot.new-helpers/resolve-remote-template  new_helpers.clj:   16
                 boot.new-helpers/resolve-template/fn  new_helpers.clj:   74
       boot.new-helpers/resolve-template/invokeStatic  new_helpers.clj:   71
                    boot.new-helpers/resolve-template  new_helpers.clj:   68
                boot.new-helpers/create_/invokeStatic  new_helpers.clj:  105
                             boot.new-helpers/create_  new_helpers.clj:   78
                 boot.new-helpers/create/invokeStatic  new_helpers.clj:  118
                              boot.new-helpers/create  new_helpers.clj:  107
                                                  ...  
                             boot.new/eval76/fn/fn/fn          new.clj:   43
                                  boot.core/run-tasks         core.clj:  938
                                    boot.core/boot/fn         core.clj:  948
                  clojure.core/binding-conveyor-fn/fn         core.clj: 1938
                                                  ...

**Comment by seancorfield** [comment]
You built a SNAPSHOT version of your template so you need `-S` on the `boot-new` command that uses it. Otherwise it only looks for a RELEASE version.
