### ISSUE TITLE
Doesn't work with http-kit template

### ISSUE THREAD

**Issue by justindbelanger** [boot-clj/boot-new#36]
The [http-kit lein template](https://github.com/http-kit/lein-template) fails with the attached error message(s).
[boot_new_http_kit_error.txt](https://github.com/boot-clj/boot-new/files/1581817/boot_new_http_kit_error.txt)
Granted, the readme does specify changes to one's ~/.lein/profiles.clj file... But I don't know if that has an bearing on this error.
I'll continue investigating as I find time for it.

**Comment by seancorfield** [comment]
It looks like the `http-kit/lein-template` is only available as a snapshot so you will need the `-S` option (or `--snapshot`) to tell `boot-new` to search for snapshots instead of releases.

**Comment by seancorfield** [comment]
Now I'm at my computer, I tried this and it worked so I'm closing this out:
```
(! 1799)-> boot -d boot/new new -t http-kit -S -n hkit
Retrieving maven-metadata.xml from https://repo.clojars.org/ (1k)
Retrieving maven-metadata.xml from https://clojars.org/repo/
Retrieving maven-metadata.xml from https://repo.clojars.org/ (1k)
Retrieving maven-metadata.xml from https://clojars.org/repo/
Retrieving maven-metadata.xml from https://clojars.org/repo/
Retrieving maven-metadata.xml from https://repo.clojars.org/ (1k)
Retrieving lein-template-1.0.0-20140103.093500-8.pom from https://repo.clojars.org/ (3k)
Retrieving lein-template-1.0.0-20140103.093500-8.jar from https://repo.clojars.org/ (99k)
have fun
```
