### ISSUE TITLE
Can't figure out how to pass args to template

### ISSUE THREAD

**Issue by lambdadelta34** [boot-clj/boot-new#43]
Hi, i tried to run something like `boot -d boot/new new -t luminus(or app template) -n guestbook -a arg1` and no matter how i write arg1, with double/single quotes, without quotes, i keep getting type error for args option.
```
boot.core/boot/fn                core.clj: 1033
...
boot.core/construct-tasks core.clj:  995
clojure.core/apply               core.clj:  646
...
boot.new/eval45/fn            new.clj:    9

java.lang.IllegalArgumentException: option :args must be of type [str]
clojure.lang.ExceptionInfo: option :args must be of type [str]
```
Any ideas?

**Comment by seancorfield** [comment]
You're using Boot 2.8.0 or 2.8.1 and it has a bug (a regression) that broke repeated arguments. Downgrade to Boot 2.7.2 until a fix is released (see the Boot 2.8.2 roadmap https://github.com/boot-clj/boot/milestone/26 ).

**Comment by lambdadelta34** [comment]
Thank you, that was the case.

**Comment by seancorfield** [comment]
Looks like Boot 2.8.2 was just released with a fix for this!
